#!/usr/bin/env sh
#
# This file was generated by Gradle.
#
# The Gradle Wrapper is licensed under the Apache License, Version 2.0.
#
# For more information see http://www.gradle.org/
#
##############################################################################
# Check for Bash
if [ -z "$BASH_VERSION" ]; then
  echo "Error: this script requires bash"
  exit 1
fi

##############################################################################
# Locate gradle-wrapper.jar (relative to script location)
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
WRAPPER_JAR="${SCRIPT_DIR}/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$WRAPPER_JAR" ]; then
  echo "Gradle wrapper jar not found: $WRAPPER_JAR"
  exit 1
fi

##############################################################################
# Setup JAVA_HOME if not set
if [ -z "$JAVA_HOME" ]; then
  JAVA_CMD=java
else
  JAVA_CMD="$JAVA_HOME/bin/java"
fi

##############################################################################
# Execute Gradle Wrapper
exec "$JAVA_CMD" -jar "$WRAPPER_JAR" "$@"

