name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download gradlew script
      run: |
        wget https://raw.githubusercontent.com/gradle/gradle/master/gradlew -O gradlew
        chmod +x gradlew

    - name: Download gradle-wrapper.jar
      run: |
        mkdir -p gradle/wrapper
        wget -O gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
  

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
