name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Convert gradlew CRLF to proper LF for Linux bash
    - name: Convert gradlew to Unix line endings
      run: sed -i 's/\r$//' gradlew

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Clean and Build
      run: ./gradlew clean build

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
